# Generated by Django 2.1.7 on 2019-04-07 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fund.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('amount_to_be_collected', models.CharField(max_length=200)),
                ('collected_amount', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to=fund.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
